version: '3.8'

services:
  api-publisher:
    build: ./api-publisher
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      GCP_PROJECT_ID: citric-adviser-485016-c6
      PUBSUB_TOPIC_ID: user-activity-events
      # THIS IS NEW: Tells the API to talk to the local emulator
      PUBSUB_EMULATOR_HOST: pubsub-emulator:8085
    depends_on:
      - pubsub-emulator
      - mongo
    networks:
      - backend-network

  # THIS SERVICE WAS MISSING
  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: gcloud beta emulators pubsub start --project=citric-adviser-485016-c6 --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"
    networks:
      - backend-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  mongo-data: